import Head from 'next/head';
import Login from 'pott/components/login/login';
import { useSelector } from 'react-redux';
import { selectIsLoggedIn } from 'pott/store/loginSlice';

export default function Home() {
    let isLoggedIn = useSelector(selectIsLoggedIn);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            {isLoggedIn ? 'logged in' : <Login/>}
        </>
    );
}
